on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: {}

name: Refresh Strava Credentials

jobs:
  refesh-creds:
    runs-on: ubuntu-latest
    name: Refresh Strava Credentials
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Setup npm
        run: npm ci
      - name: Fetch credentials
        env:
          STRAVA_EMAIL: ${{ secrets.STRAVA_EMAIL }}
          STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
        run: |
          eval "$(node scripts/refresh_strava_credentials.js)"
          echo "::add-mask::${STRAVA_ID}"
          echo "::add-mask::${STRAVA_COOKIES}"
          echo "STRAVA_ID=${STRAVA_ID}" >> $GITHUB_ENV
          echo "STRAVA_COOKIES=${STRAVA_COOKIES}" >> $GITHUB_ENV

      - name: Write Strava creds to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            STRAVA_ID
            STRAVA_COOKIES
